import type { FetchPage, IdentityProbe, JobSource, LiveStatus, ParsedPosting, RawPosting, SourceDescriptor } from "../types";
import { buildDemoJobs, DEMO_EMPLOYERS, type DemoEmployer, type DemoJob } from "./data";
import { DemoCommunityBoard } from "./community-board";

const DAY = 24 * 60 * 60 * 1000;

/**
 * One demo "employer board" per fictional employer. Every record it produces
 * is flagged is_demo and the UI shows a persistent Demo data banner.
 */
export class DemoSource implements JobSource {
  readonly descriptor: SourceDescriptor;

  constructor(
    private readonly employer: DemoEmployer,
    private readonly jobs: DemoJob[],
    private readonly now: () => Date = () => new Date(),
  ) {
    this.descriptor = {
      key: `demo:${employer.slug}`,
      type: "DEMO",
      provider: "demo",
      name: `${employer.name} — demo job board`,
      boardToken: employer.slug,
      termsReference: "Fictional data generated by Provenant (src/sources/demo). No third-party content.",
      allowedUse: "Any use. Must always be labelled as demo data.",
      rateLimitPerMin: 10_000,
      isDemo: true,
      employerOwned: true,
      employerHint: {
        name: employer.name,
        domain: employer.domain,
        careersUrl: employer.careersLinksBoard ? `https://${employer.domain}/careers` : undefined,
      },
    };
  }

  async fetch(_cursor: string | null): Promise<FetchPage> {
    return {
      // Jobs older than 25 days have been taken down by the (demo) employer.
      postings: this.jobs.filter((j) => j.postedDaysAgo <= 25).map((j) => ({ externalRef: j.externalRef, payload: j })),
      nextCursor: null,
    };
  }

  parse(raw: RawPosting): ParsedPosting {
    const j = raw.payload as DemoJob;
    const url = `https://jobs.${this.employer.domain}/${j.externalRef}`;
    return {
      externalRef: j.externalRef,
      title: j.title,
      employerName: this.employer.name,
      locationText: `${j.city}, ${j.province}`,
      employmentTypeText: j.employmentType,
      workplaceTypeText: j.workplace,
      descriptionText: j.description,
      url,
      applyUrl: `${url}/apply`,
      postedAt: new Date(this.now().getTime() - j.postedDaysAgo * DAY),
      salary: null, // parsed from the description so the evidence quotes the posting's own sentence
      skills: j.skills,
    };
  }

  async checkLive(externalRef: string): Promise<LiveStatus> {
    const job = this.jobs.find((j) => j.externalRef === externalRef);
    const checkedAt = this.now();
    // Demo rule: postings older than 25 days have been taken down, so freshness has something to show.
    if (!job || job.postedDaysAgo > 25) {
      return { state: "GONE", checkedAt, detail: "Removed from the demo employer board" };
    }
    return { state: "LIVE", checkedAt, detail: "Listed on the demo employer board" };
  }

  /** Demo stand-in for fetching the careers page: the fixture says whether it links the board. */
  async probeIdentity(): Promise<IdentityProbe> {
    const checkedAt = this.now();
    const careersUrl = `https://${this.employer.domain}/careers`;
    return this.employer.careersLinksBoard
      ? { linked: true, checkedAt, evidenceUrl: careersUrl, detail: `${careersUrl} (demo) links to this job board.` }
      : { linked: false, checkedAt, evidenceUrl: careersUrl, detail: `${careersUrl} (demo) doesn't link to this job board.` };
  }
}

export function createDemoSources(now?: () => Date): JobSource[] {
  const all = buildDemoJobs();
  return [
    ...DEMO_EMPLOYERS.map((e) => new DemoSource(e, all.filter((j) => j.employerSlug === e.slug), now)),
    new DemoCommunityBoard(all, now),
  ];
}
